# Generated by Django 3.0.5 on 2020-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
