# Generated by Django 3.0.5 on 2020-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20200414_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='gym/images'),
        ),
    ]
