# Generated by Django 3.0.5 on 2020-04-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_disc_health_muscle_ninja_saiyan_tonned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disc',
        ),
        migrations.DeleteModel(
            name='health',
        ),
        migrations.DeleteModel(
            name='muscle',
        ),
        migrations.DeleteModel(
            name='ninja',
        ),
        migrations.DeleteModel(
            name='saiyan',
        ),
        migrations.DeleteModel(
            name='tonned',
        ),
    ]
