# Generated by Django 3.0.5 on 2020-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_ninja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='emails',
            new_name='ninjaemail',
        ),
    ]
