# Generated by Django 3.0.5 on 2020-04-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20200415_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='ages',
            new_name='ninjaages',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='habit',
            new_name='ninjahabit',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='height',
            new_name='ninjaheight',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='message',
            new_name='ninjamessage',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='phones',
            new_name='ninjaphone',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='weight',
            new_name='ninjaweight',
        ),
    ]
