# Generated by Django 3.0.5 on 2020-04-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_auto_20200416_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjaages',
            new_name='ages',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjaemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjahabit',
            new_name='habit',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjaheight',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjamessage',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjaphone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='ninjaweight',
            new_name='weight',
        ),
    ]
